using System.Diagnostics.CodeAnalysis;

namespace Starsbane.AI
{
    public interface IVideoGenerator : IDisposable
    {
        /// <summary>
        /// Sends an video generation request and returns the generated video as a <see cref="VideoGenerationResponse"/>.
        /// </summary>
        /// <param name="request">The video generation request containing the prompt and optional original videos for editing.</param>
        /// <param name="options">The video generation options to configure the request.</param>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
        /// <exception cref="ArgumentNullException"><paramref name="request"/> is <see langword="null"/>.</exception>
        /// <returns>The videos generated by the <see cref="VideoGenerationRequest"/>.</returns>
        Task<VideoGenerationResponse> GenerateAsync(VideoGenerationRequest request, VideoGenerationOptions? options = null, CancellationToken cancellationToken = default);

        /// <summary>Asks the <see cref="IVideoGenerator"/> for an object of the specified type <paramref name="serviceType"/>.</summary>
        /// <param name="serviceType">The type of object being requested.</param>
        /// <param name="serviceKey">An optional key that can be used to help identify the target service.</param>
        /// <returns>The found object, otherwise <see langword="null"/>.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="serviceType"/> is <see langword="null"/>.</exception>
        /// <remarks>
        /// The purpose of this method is to allow for the retrieval of strongly typed services that might be provided by the <see cref="IVideoGenerator"/>,
        /// including itself or any services it might be wrapping.
        /// </remarks>
        object? GetService(Type serviceType, object? serviceKey = null);
    }
}
