using System.Diagnostics.CodeAnalysis;

namespace Starsbane.AI
{
    public interface ISpeechGenerator : IDisposable
    {
        /// <summary>
        /// Sends an speech generation request and returns the generated speech as a <see cref="SpeechGenerationResponse"/>.
        /// </summary>
        /// <param name="request">The speech generation request containing the prompt and optional original speechs for editing.</param>
        /// <param name="options">The speech generation options to configure the request.</param>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> to monitor for cancellation requests. The default is <see cref="CancellationToken.None"/>.</param>
        /// <exception cref="ArgumentNullException"><paramref name="request"/> is <see langword="null"/>.</exception>
        /// <returns>The speechs generated by the <see cref="SpeechGenerationRequest"/>.</returns>
        Task<SpeechGenerationResponse> GenerateAsync(SpeechGenerationRequest request, SpeechGenerationOptions? options = null, CancellationToken cancellationToken = default);

        /// <summary>Asks the <see cref="ISpeechGenerator"/> for an object of the specified type <paramref name="serviceType"/>.</summary>
        /// <param name="serviceType">The type of object being requested.</param>
        /// <param name="serviceKey">An optional key that can be used to help identify the target service.</param>
        /// <returns>The found object, otherwise <see langword="null"/>.</returns>
        /// <exception cref="ArgumentNullException"><paramref name="serviceType"/> is <see langword="null"/>.</exception>
        /// <remarks>
        /// The purpose of this method is to allow for the retrieval of strongly typed services that might be provided by the <see cref="ISpeechGenerator"/>,
        /// including itself or any services it might be wrapping.
        /// </remarks>
        object? GetService(Type serviceType, object? serviceKey = null);
    }
}
